//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DropDownCaseCading.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonalInfo
    {
        public int PersonID { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public System.DateTime BirthDate { get; set; }
        public decimal MobileNumber { get; set; }
        public string Education { get; set; }
        public string Email { get; set; }
        public string Religion { get; set; }
        public string Cast { get; set; }
        public string SubCast { get; set; }
        public string Country { get; set; }
        public string State { get; set; }
        public string City { get; set; }
        public string Taluka { get; set; }
        public string Relation { get; set; }
    }
}
